# Linear Algebra with Python

Python is a general-purpose programming language with a broad ecosystem of tools for scientific computing. It is widely used for machine learning, applied mathematics, and artificial intelligence. We will use it here to facilitate computations that aren't feasible to perform by hand.

## Imports

There are two Python libraries that we will start with: the first is NumPy ("Numeric Python") and the second is SciPy ("Scientific Python"). From the second, we are primarily going to use the linear algebra submodule. As these libraries are outside of base Python, you need to import them to use them. Below, I am importing them, using a conventional abbreviation for NumPy.

In [1]:
import numpy as np
import scipy.linalg as linalg

## NumPy ndarrays

NumPy is built around a single object: a multidimensional array object called an ndarray that is a generalization of the matrix definition that we are working with in this course. A matrix as we have defined it is a two-dimensional NumPy ndarray.

NumPy does define a matrix object, but its use is not recommended. Here is an example of defining a matrix as an ndarray.

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


As you can see, the array is specified as a list of lists. Each of the nested lists corresponds to a row of the array. Indexing the array follows the row-first, column-second convention, but bear in mind that Python uses zero-based indexing!

In [6]:
print(A[1, 1], A[0, 2]) 

5 3


In [7]:
print(A[2, 3])

IndexError: index 2 is out of bounds for axis 0 with size 2

The error above occurred because I asked for the entry in row two of $A$, but using zero-based indexing there exist only rows 0 and 1 in $A$.

Some attributes of a NumPy ndarray differ from usual matrix terminology. For instance, the dimension of an array is its shape:

In [9]:
A.shape

(2, 3)

Again note that this follows the row first, column second convention. 

Vectors are NumPy ndarrays also. However, there are a couple of caveats to be aware of when work with them. First, 

In [10]:
v = np.array([[1], [2], [3]])
w = np.array([1, 2, 3])

In [11]:
v

array([[1],
       [2],
       [3]])

In [12]:
w

array([1, 2, 3])

In [13]:
v == w

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])